[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.12.0"
"@openzeppelin-contracts" = "5.2.0"
cartesi-rollups-contracts = "2.1.1"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
